# Generated by Django 5.0.6 on 2024-07-15 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students_enrolled",
            field=models.ManyToManyField(
                related_name="enrolled_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="students_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
