# Generated by Django 5.0.6 on 2024-07-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_course_students_enrolled_alter_course_instructor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="enrolled_on",
            new_name="date_enrolled",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="myapp.course",
            ),
        ),
    ]
