# Generated by Django 5.0.6 on 2024-07-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_forum_quiz_resource_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="courses_enrolled",
            field=models.ManyToManyField(
                related_name="enrolled_users", to="myapp.course"
            ),
        ),
    ]
